<?php

namespace App\Http\Requests\Users;

use App\Rules\Iban;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Auth;

class ClientCompleteProfileRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array|string>
     */
    public function rules(): array
    {
        $user = Auth::user();
        $isArtist = $user->role == 'artist';

        return [
            "phone" => "required|unique:users,phone," . Auth::user()->id,
            "phone_prefix" => "nullable",
            "name" => "required",
            // [SECURITY][R2-H5] Profile photo is stored on the public disk and web-served, so
            // restrict it to real images with a size cap (previously unvalidated → an attacker
            // could upload .svg/.html for stored XSS, or oversized files for storage abuse). The
            // filename is already server-generated by Storage::put().
            "profile_photo" => "nullable|file|mimetypes:image/jpeg,image/png,image/webp|max:5120",
            "email" => "required|unique:users,email," . Auth::user()->id,
            "dob" => "required",
            "gender" => "required|in:male,female",
            "city_id" => "required",
            "city" => "required|string",
            "latitude" => "required",
            "longitude" => "required",
            "vat_number" => "nullable|digits_between:1,16",
            "cr_number" => "nullable|digits_between:1,16",
            "facebook" => "nullable",
            "instagram" => "nullable",
            "youtube" => "nullable",
            "snapchat" => "nullable",
            "whatsapp" => "nullable",
            "start_date" => $isArtist ? "required" : "nullable",
            "end_date" => $isArtist ? "required" : "nullable",
        ];
    }
}
